config/routes.rb
Rails.application.routes.draw do
  
  # Routes for main resources
  resources :items
  resources :purchases
  resources :item_prices
  resources :users
  resources :orders
  resources :order_items
  resources :schools
  resources :sessions

  # authentication routes
  get 'user/edit' => 'users#edit', :as => :edit_current_user
  get 'signup' => 'users#new', :as => :signup
  get 'login' => 'home#home', :as => :login
  get 'logout' => 'sessions#destroy', :as => :logout

  get 'index' => 'carts#index', :as => :index
  get 'add_to_cart/:id' => 'carts#add_to_cart', :as => :add_to_cart
  get 'remove_from_cart/:id' => 'carts#remove_from_cart', :as => :remove_from_cart
  get 'destroy_order/:id' => 'orders#destroy', :as => :destroy_order

  # Semi-static page routes
  get 'home' => 'home#home', as: :home
  get 'about' => 'home#about', as: :about
  get 'contact' => 'home#contact', as: :contact
  get 'privacy' => 'home#privacy', as: :privacy
  patch 'ship/:id' => 'order_items#ship', as: :ship
  
  # Set the root url
  root :to => 'sessions#new', as: :root

end

app/views/partials/_address_info.html.erb
  <%= school.street_1 %><br />
  <% unless school.street_2.blank? %>
    <%= school.street_2 %><br />
  <% end %>
  <%= school.city %>, <%= school.state %> <%= school.zip %>

app/views/partials/_display_form.html.erb
<div class="row">
  <div class="small-12 columns">
    <%= render :partial => "form" %>
  </div>
</div>

app/views/partials/_flash.html.erb
<% flash.each do |name, msg| %>
  <div data-alert data-options="animation_speed:500, animation:'fadeOut';" class="alert-box <%= flash[:notice] ? "success" : "warning" %> radius">
    <a href="#" class="close">&times;</a>
    <%= msg %>
  </div>
<% end %>

app/views/partials/_footer.html.erb
<footer>
<div id="footer-links">
	<%= link_to 'Home', home_path %>&nbsp;&nbsp; | &nbsp;&nbsp;
  <%= link_to 'About A&M', about_path %>&nbsp;&nbsp; | &nbsp;&nbsp;
	<%= link_to 'Contact Us', contact_path %>&nbsp;&nbsp; | &nbsp;&nbsp;
	<%= link_to 'Privacy Policy', privacy_path %>
</div>
	<br/>
	
	<div id="signature">
		Webmaster: <%= mail_to("sallyz@andrew.cmu.edu", "Sally Zhao", encode: "javascript") %> 
		&nbsp;&nbsp;&copy 2017
	</div>
	
	<br/>

</footer>

app/views/partials/_inactive.html.erb
<h3> Inactive Items </h3>
<table>
  <tr>
    <th> Name </th>
  </tr>

  <tbody>
    <% for item in items.alphabetical %>
      <tr>
        <td> <%= item.name %> </td>
      </tr>
    <% end %>
  </tbody> 
</table>

app/views/partials/_index_structure.html.erb
<div class="row">
  <div class="small-8 columns" id="main_div">
    <!-- primary partial gets displayed here in main div -->
    <%= render partial: "#{primary}" %>
    <!-- sometimes we want another partial below -->
    <% unless secondary.nil? %>
      <p>&nbsp;</p>
      <%= render partial: "#{secondary}" %>
    <% end %>
    
  </div>
  <div class="small-6 columns">
    <!-- render the sidebar, if it exists -->
    <%= render partial: "#{sidebar}" unless sidebar.blank? %>
  </div>
</div>

<!-- Add a button for new instances of object -->
<% if logged_in? %>
  <% if current_user.role == "manager" || current_user.role == "admin" %>
    <%= link_to(eval("new_#{model_name}_path"), class: "button radius", id: "new_purchase_link") do %>
      <!-- <i class="fa fa-plus"></i> -->
      &nbsp;Add a New <%= model_name.capitalize %>
    <% end %>
  <% end %> 
<% end %>

app/views/partials/_index_structure_2.html.erb
<div class="row">
  <div class="small-9 columns">
    <!-- primary partial gets displayed here in main div -->
    <%= render partial: "#{primary}" %>
    <!-- sometimes we want another partial below -->
    <% unless secondary.nil? %>
      <p>&nbsp;</p>
      <%= render partial: "#{secondary}" %>
    <% end %>
    
  </div>
  <div class="small-3 columns">
    <!-- Add a button for new instances of object -->
    <%= link_to(eval("new_#{model_name}_path"), class: "button radius") do %>
      <!-- <i class="fa fa-plus"></i> -->
      &nbsp;Add a New <%= model_name.capitalize %>
    <% end %>
  </div>
</div>

app/views/partials/_items_index.html.erb
<!-- <table>
  <thead> <%#= category %> </thead>
  <tr>
    <th> Name </th>
    <th> Price </th>
    <th> Inventory </th>
  </tr>

  <tbody>
    <%# for item in items.alphabetical %>
      <tr>
        <td> <%#= link_to item.name, item_path(item), class: 'item-name' %> </td>
        <td> <%#= number_to_currency(item.current_price) %> </td>
        <td> <%#= item.inventory_level %> </td>
      </tr>
    <%# end %>
  </tbody> 
</table> -->

app/views/partials/_nav.html.erb
<div class="contain-to-grid" >
  <nav class="top-bar" data-topbar role="navigation"> 
    <section class="top-bar-section" id="navbar">
      <ul >
        <!-- link to home -->
        <!-- <li><img src="assets/logo.png" alt="logo" id="logo"/><li> -->
        <li><%= link_to image_tag("logo.png"), home_path, id: "logo" %></li>

        <!-- options for items -->
        <span id="links">
        <% if logged_in? %>
          <% if current_user.role != "shipper" && current_user.role != "customer" %>
            <li class="has-dropdown">
              <%= link_to "ITEMS", items_path %>
              <ul class="dropdown">
                <li><%= link_to "Add an Item", new_item_path %></li>
              </ul>
            </li>
          <% else %> 
            <li><%= link_to "ITEMS", items_path %></li>
          <% end %> 
          

        <!-- options for purchases -->
          <% if current_user.role != "shipper" && current_user.role != "customer" %>
            <li>
              <%= link_to "PURCHASES", purchases_path %>
            </li>
          <% end %>

          <!-- options for prices -->
          <% if current_user.role != "shipper" && current_user.role != "customer" %>
            <!-- <li>
              <%#= link_to "PRICES", item_prices_path %>
            </li> -->
          <% end %>

          <% if current_user.role != "shipper" %>
          <li>
            <%= link_to "SCHOOLS", schools_path %>
          </li>
          <% end %>

          <% if current_user.role == "manager" || current_user.role == "admin" %>
            <li><%= link_to "USERS", users_path %></li>
            <li><%= link_to "ORDERS", orders_path %></li>
          <% end %>

          <li class="has-dropdown right">
            <%= link_to current_user.first_name.upcase, user_path(current_user) %>
            <ul class="dropdown">
              <!-- <li><%#= link_to "My Orders", orders_path %></li> -->
              <li><%= link_to "My Cart", index_path %></li>
              <li><%= link_to 'Logout', logout_path %></li>
            </ul>
          </li>

        <% else %>
          <!-- Guests -->
          <li><%= link_to "ITEMS", items_path %></li>
        <% end %>

        <!-- content once logged in goes here -->
        <% if !logged_in? %>
          <li class="right"><%= link_to 'LOGIN', root_path %></li>
          <li class="right"><%= link_to 'SIGN UP', new_user_path %></li>
        <% end %>

      </span><!-- links -->
      </ul>
    </section>
  </nav>
</div>

app/views/partials/_object_options.html.erb
  <% opt = "#{object.respond_to?(:name) ? object.name : model_name.capitalize }" %>

  <div class="form-actions">
    
    <%= link_to(eval("edit_#{model_name}_path(object)"), class: 'button radius') do %>
        &nbsp;<%= "Edit #{opt}" %>
    <% end %>
    &nbsp;&nbsp;
    
    <%= link_to(eval("#{model_name}_path(object)"), method: 'delete', data: {confirm: "Are you sure you want to permanently delete #{opt}"}, class: 'button radius alert') do %>
        &nbsp;<%= "Delete #{opt}" %>
    <% end %>
  </div>

app/views/partials/_price_history.html.erb
<table id="ph-table">
  <thead> Price History </thead>
  <tr>
    <th> Price </th>
    <th> Start Date </th>
  </tr>

  <tbody>
    <% prices.chronological.each do |price| %>
      <tr>
        <td> <%= number_to_currency(price.price) %> </td>
        <td> <%= price.start_date.strftime('%m/%d/%y') %> </td>
      </tr>
    <% end %>
  </tbody> 
</table>

app/views/partials/_reorder.html.erb
<table>
  <thead> Dashboard </thead>
  <tr>
    <th> Reorder List </th>
    <th> Inventory </th>
    <th> Reorder Level </th>
  </tr>

  <tbody> 
    <% @items_to_reorder.each do |item| %>
      <tr>
        <td> <%= item.name %> </td>
        <td> <%= item.inventory_level %> </td>
        <td> <%= item.reorder_level %> </td>
      </tr>
    <% end %>
  </tbody> 
</table>

app/views/partials/_show_structure.html.erb
<div class="row">
  <div class="small-7 columns">
    <!-- primary partial gets displayed here in main div -->
    <%= render partial: "#{primary}" %>
    <!-- sometimes we want another partial below -->
    <% unless secondary.nil? %>
      <p>&nbsp;</p>
      <%= render partial: "#{secondary}" %>
    <% end %>
    
  </div>
  <div class="small-5 columns">
    <!-- render the sidebar, if it exists -->
    <%= render partial: "#{sidebar}" unless sidebar.blank? %>
  </div>
</div>

<!-- Add buttons to list all, edit project or destroy object -->
<%= render partial: "partials/object_options", locals: {model_name: "#{model_name}", object: @object}  %>

app/views/partials/_similar.html.erb
<table id="similar-table">
  <thead> Similar Items </thead>
  <tr>
    <th> Name </th>
    <th> Price </th>
  </tr>

  <tbody>
    <% items.each do |item| %>
      <tr>
        <td> <%= item.name %> </td>
        <td> <%= number_to_currency(item.current_price) %> </td>
      </tr>
    <% end %>
  </tbody> 
</table>
  