config/routes.rb
Rails.application.routes.draw do
  
  # Routes for main resources
  resources :items
  resources :purchases
  resources :item_prices
  resources :users
  resources :orders
  resources :order_items
  resources :schools
  resources :sessions

  # authentication routes
  get 'user/edit' => 'users#edit', :as => :edit_current_user
  get 'signup' => 'users#new', :as => :signup
  get 'login' => 'home#home', :as => :login
  get 'logout' => 'sessions#destroy', :as => :logout

  get 'index' => 'carts#index', :as => :index
  get 'add_to_cart/:id' => 'carts#add_to_cart', :as => :add_to_cart
  get 'remove_from_cart/:id' => 'carts#remove_from_cart', :as => :remove_from_cart
  get 'destroy_order/:id' => 'orders#destroy', :as => :destroy_order

  # Semi-static page routes
  get 'home' => 'home#home', as: :home
  get 'about' => 'home#about', as: :about
  get 'contact' => 'home#contact', as: :contact
  get 'privacy' => 'home#privacy', as: :privacy
  patch 'ship/:id' => 'order_items#ship', as: :ship
  
  # Set the root url
  root :to => 'sessions#new', as: :root

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  #before_action :check_login, except: [:index, :show]
  
  def home
    @items_to_reorder = Item.need_reorder.alphabetical.to_a
    @not_shipped = OrderItem.unshipped

    if logged_in?
      @my_orders = current_user.orders.chronological.to_a
      #@schools = current_user.orders.for_school(2)
    end
  end

  def about
  end

  def contact
  end

  def privacy
  end

  def complete
    
  end
  
end

app/views/home/_general_home.html.erb
<h3 style="margin-left: 37%;">WELCOME TO A&M</h3> <hr/><br/>
<br />
<div class="row">
	<div >
		<img style="margin-top: -20px;" src="assets/guest_home.jpg" alt="chess img" id="guest_home"/>

		<%= link_to "Explore our Products", items_path, id: "explore" %>
		<!-- <h4 id="explore"> Explore our Products </h4> -->

	</div>

</div>

app/views/home/_not_shipped.html.erb
<div id="not_shipped_table">
<h3 id="center_heading">NOT SHIPPED</h3>
<hr/> <br />

<% unless @not_shipped.nil? || @not_shipped.empty? %>
  <table style="margin: 0px auto;" class="table table-striped">
    <thead>
      <tr>
        <th width="90">Order ID</th>
        <th width="150">Item Name</th>
        <th width="75">Quantity</th>
        <th width="150">Shipped On</th>
        <th> Ship </th>
      </tr>
    </thead>
    <tbody>
      <% @not_shipped.each do |order_item| %>
          <tr>
            <td class="gold"><%= link_to order_item.order.id, order_path(order_item.order), id: "order_id" %></td>
            <td><%= link_to order_item.item.name, item_path(order_item.item) %></td>
            <td><%= order_item.quantity %></td>
            <td><%= order_item.shipped_on %></td>
            <td> <%= link_to(ship_path(order_item), class: 'button tiny radius', id: 'ship_link', remote: true, method: 'patch') do %> Ship <% end %> </td>
          </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p>There are no items that need to be reorder at this time.</p>
<% end %>
</div>
<br/><br/>

app/views/home/_reorder_list.html.erb
<h3 id="center_heading">REORDER LIST</h5> <hr /> <br />

<% unless @items_to_reorder.nil? || @items_to_reorder.empty? %>
  <table style="margin: 0px auto;" class="table table-striped">
    <thead>
      <tr>
        <th width="250">Name</th>
        <th width="125">Inventory</th>
        <th width="125">Reorder Level</th>
      </tr>
    </thead>
    <tbody>
      <% @items_to_reorder.each do |item| %>
        <tr>
          <td><%= link_to item.name, item_path(item), {:style=>'color: #bb892a;'} %></td>
          <td><%= item.inventory_level %></td>
          <td><%= item.reorder_level %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p>There are no items that need to be reorder at this time.</p>
<% end %>

app/views/home/about.html.erb
<br />
<div class="row">
  <div class="small-7 columns home_description">
    <h2>About A&M</h2> <br />

    <p>
    	A&M believes in the importance of scholastic chess.  To help support 
        scholastic chess, we make chess equipment available to schools and other educational 
        organizations at wholesale prices.  This chess equipment is only available to schools; 
        we do not sell to individuals.
    </p>
    <p>&nbsp;</p>
    <p>&nbsp;</p>
    <p>&nbsp;</p>
    <p>&nbsp;</p>
    <p>&nbsp;</p>
  </div>
</div>

app/views/home/contact.html.erb
<br />
<div class="row">
	<div class="small-7 columns">
		<h2>Contact A&M</h2>
		<p class="supertiny">&nbsp;</p>
		<table cellpadding="3">
			<tr>
				<td>Webmaster:&nbsp;&nbsp;&nbsp;</td>
				<td>Sally Zhao</td>
			</tr>
			<tr>
				<td>Email:</td>
				<td>
				<%= mail_to("sallyz@andrew.cmu.edu", "sallyz@andrew.cmu.edu", :encode => "javascript") %> 
				</td>
			</tr>
			<tr>
				<td>Phone:</td>
				<td>412-268-8211</td>
			</tr>
		</table>
			
		<p>&nbsp;</p>
		<p>&nbsp;</p>
		<p>&nbsp;</p>
		<p>&nbsp;</p>
	</div>
</div>

app/views/home/home.html.erb
<% if logged_in? %>
  <% if current_user.role == "admin" %> 
    <%= render :partial => 'reorder_list' %>
  <% elsif current_user.role == "manager" %> 
    <%= render :partial => 'reorder_list' %>
    </br>
    <%= render :partial => 'not_shipped' %>
    <%#= render :partial => 'not_shipped' %>
    <% elsif current_user.role == "shipper" %>
      <%= render :partial => 'not_shipped' %>
    <% elsif current_user.role == "customer" %>
      <%= render :partial => 'orders/my_orders' %>
  <% end %>
<% else %>
      <%= render :partial => 'general_home' %>
<% end %>

app/views/home/privacy.html.erb
<br />
<div class="row">
	<div class="small-8 columns home_description">
		<h2>A&M Privacy Policy</h2>
		<br />

		<p>The A&M privacy policy is very simple, rarely  
			changes, and does not require a lawyer to understand it.  
			We will pounce on the opportunity to sell every bit of information 
			on you they have at our disposal.  We will gladly sell your address, 
			phone, email, age, name of pet, name of favorite superhero, color of 
			bunny slippers you wear at home, and the like, to any willing buyer 
			who will pay the big bucks.  (BTW, we <em>know</em> you wear bunny 
			slippers at home and we know what color they are.  You really have 
			no secrets from this crew.)  If you have sensitive information that 
			you don't want us to share with the world, then keep it to yourself 
			-- don't tell us.  
			<br><br>
			It's really that simple.
		</p>

		<p>&nbsp;</p>
		<br />
	</div>
</div>