config/routes.rb
Rails.application.routes.draw do
  
  # Routes for main resources
  resources :items
  resources :purchases
  resources :item_prices
  resources :users
  resources :orders
  resources :order_items
  resources :schools
  resources :sessions

  # authentication routes
  get 'user/edit' => 'users#edit', :as => :edit_current_user
  get 'signup' => 'users#new', :as => :signup
  get 'login' => 'home#home', :as => :login
  get 'logout' => 'sessions#destroy', :as => :logout

  get 'index' => 'carts#index', :as => :index
  get 'add_to_cart/:id' => 'carts#add_to_cart', :as => :add_to_cart
  get 'remove_from_cart/:id' => 'carts#remove_from_cart', :as => :remove_from_cart
  get 'destroy_order/:id' => 'orders#destroy', :as => :destroy_order

  # Semi-static page routes
  get 'home' => 'home#home', as: :home
  get 'about' => 'home#about', as: :about
  get 'contact' => 'home#contact', as: :contact
  get 'privacy' => 'home#privacy', as: :privacy
  patch 'ship/:id' => 'order_items#ship', as: :ship
  
  # Set the root url
  root :to => 'sessions#new', as: :root

end

app/models/order.rb
class Order < ActiveRecord::Base
  # get module to help with some functionality
  include ChessStoreHelpers::Validations
  include ChessStoreHelpers::Shipping
  require 'base64'

  # Relationships
  has_many :order_items
  has_many :items, through: :order_items
  belongs_to :school
  belongs_to :user

  # Virtual attributes (non-saved)
  attr_accessor :credit_card_number
  attr_accessor :expiration_year
  attr_accessor :expiration_month
  attr_reader :destroyable

  # Scopes
  scope :chronological, -> { order(date: :desc) }
  scope :paid,          -> { where.not(payment_receipt: nil) }
  scope :for_school,    ->(school_id) { where(school_id: school_id) }

  # Class methods
  def self.not_shipped
    joins(:order_items).where("order_items.shipped_on IS NULL").uniq!
  end

  # Validations
  # validates_date :date  # not essential, but permittable
  validates_numericality_of :grand_total, greater_than_or_equal_to: 0, allow_blank: true
  validate :user_is_active_in_system
  validate :school_is_active_in_system
  validate :credit_card_number_is_valid
  validate :expiration_date_is_valid

  # Other methods
  def pay
    return false unless self.payment_receipt.nil?
    generate_payment_receipt
    self.save!
    self.payment_receipt
  end

  def total_weight
    weight = self.order_items.inject(0){|sum, oi| sum += oi.item.weight * oi.quantity}
  end

  def shipping_costs
    calculate_shipping_costs(self.total_weight, base=5.00)
  end

  def credit_card_type
    credit_card.type.nil? ? "N/A" : credit_card.type.name
  end

  # Callbacks
  before_create :set_date_if_not_given
  before_destroy :is_destroyable?
  # after_destroy :remove_unshipped_order_items
  # after_rollback :remove_remaining_unshipped_order_items
  after_rollback :remove_unshipped_order_items
  
  private
  def user_is_active_in_system
    is_active_in_system(:user)
  end

  def school_is_active_in_system
    is_active_in_system(:school)
  end
  
  def set_date_if_not_given
    unless self.date && self.date.is_a?(Date)
      self.date = Date.current
    end
  end

  def generate_payment_receipt
    self.payment_receipt = Base64.encode64("order: #{self.id}; amount_paid: #{self.grand_total}; received: #{self.date}; card: #{self.credit_card_type} ****#{self.credit_card_number[-4..-1]}")
  end

  def credit_card
    CreditCard.new(self.credit_card_number, self.expiration_year.to_i, self.expiration_month.to_i)
  end

  def credit_card_number_is_valid
    return false if self.expiration_year.nil? || self.expiration_month.nil?
    if self.credit_card_number.nil? || credit_card.type.nil?
      errors.add(:credit_card_number, "is not valid")
      return false
    end
    true
  end

  def expiration_date_is_valid
    return false if self.credit_card_number.nil? 
    if self.expiration_year.nil? || self.expiration_month.nil? || credit_card.expired?
      errors.add(:expiration_year, "is expired")
      return false
    end
    true
  end

  def is_destroyable?
    @destroyable = self.order_items.shipped.empty?
    remove_unshipped_order_items
    return @destroyable
  end

  def remove_unshipped_order_items
    self.order_items.unshipped.each{ |oi| oi.destroy } unless destroyable.nil?
  end
  
  # def remove_remaining_unshipped_order_items
  #   if !destroyable.nil? && destroyable == false
  #     remove_unshipped_order_items
  #   end
  #   @destroyable = nil
  # end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]
  before_action :check_login, except: [:new, :create]
  authorize_resource

  include ChessStoreHelpers::Cart
  include ChessStoreHelpers::Shipping

  def index
    @orders = Order.chronological.paginate(:page => params[:page]).per_page(10)
    @my_orders = current_user.orders.chronological.paginate(:page => params[:page]).per_page(5)
  end

  def show
    @order_items = @order.order_items.to_a
  end

  def new
    @order = Order.new
    @cart_items = get_list_of_items_in_cart
    @total_cost = calculate_cart_items_cost
    @shipping_cost = calculate_cart_shipping
    @grand_total = @total_cost + @shipping_cost
  end

  def edit
    
  end

  def create
    @order = Order.new(order_params)
    @order.update_attributes(:grand_total => calculate_cart_items_cost + calculate_cart_shipping) 
    if @order.save
      redirect_to orders_path, notice: "Your order has been placed!"
      save_each_item_in_cart(@order)
      @order.pay
      clear_cart
    else
      flash[:error] = "This order could not be created."
      render "new"
    end
  end

  def update
    if @order.update_attributes(order_params)
      flash[:notice] = "#{@order.id} is updated."
      redirect_to @order
    else
      render :action => 'edit'
    end
  end

  def destroy
    @order.destroy
    flash[:notice] = "Successfully removed #{@order.id} from Chess Direct."
    redirect_to orders_url
  end

  private
    def set_order
      @order = Order.find(params[:id])
    end

    def order_params
      params.require(:order).permit(:date, :school_id, :user_id, :payment_receipt, :credit_card_number, :expiration_month, :expiration_year)  
    end
end

app/views/orders/_my_orders.html.erb
<% if @my_orders.nil? || @my_orders.empty? %>
  <h4>YOU HAVE NO ORDERS</h4> <hr />
  <%= link_to(items_path, class: 'button radius') do %>
    SHOP NOW
  <% end %>
<% else %>
  <h4>Orders</h4>
  <table class="table table-striped">
    <thead>
      <tr>
        <th width="225">Order ID</th>
        <th width="225">Date</th>
        <th width="150">School</th>
        <th width="150">User</th>
        <th width="150">Shipped</th>
        <th width="150">Grand Total</th>
        <th width="150">Payment Confirmation</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @my_orders.each do |order| %>
        <tr>
          <td><%= link_to order.id, order_path(order) %></td>
          <td><%= order.date.strftime('%m/%d/%y') %></td>
          <td><%= order.school_id %></td>
          <td><%= order.user_id %></td>
          <td><%= Order.not_shipped.include?(order) %></td>
          
          <td><%= number_to_currency(order.grand_total) %></td>
          <td><%= order.payment_receipt %></td>
          <% if !Order.not_shipped.include?(order) %>
            <td><%= link_to(destroy_order_path(order.id), class: 'tiny button radius') do %>
              Destroy
            <% end %> </td>
          <% else %>
            <td> </td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>
<p>&nbsp;</p>

app/views/orders/_new_order_form.html.erb
<h3 id="center_heading"> CHECKOUT </h3> <hr/> <br/>

<% unless @cart_items.nil? || @cart_items.empty? %>
  <table class="table table-striped" id="checkout_table">
    <thead>
      <tr>
        <th width="300">Order ID</th>
        <th> Price </th>
        <th> Quantity </th>
        <th> Subtotal </th>
        <th> </th>
      </tr>
    </thead>
    <tbody>
      <% @cart_items.each do |order_item| %>
        <tr>
          <td><%= link_to order_item.item.name, item_path(order_item.item.id), {:style=>'color: #bb892a;'} %></td>
          <td> <%= number_to_currency(order_item.item.current_price) %> </td>
          <td> <%= order_item.quantity %> </td>
          <td> <%= number_to_currency(order_item.subtotal) %> </td>
          <td><%= link_to "Remove", remove_from_cart_path(order_item.item.id), {:style=>'color: #bb892a;'} %> </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <div id="costs">
    <p> Order Subtotal: <%= number_to_currency(@total_cost) %> </p>
    <p> Shipping Cost : <%= number_to_currency(@shipping_cost) %> </p>
    <p style="color: #bb892a;"> Grand Total : <%= number_to_currency(@grand_total) %> </p>
  </div>

<% else %>
    No items in the cart
<% end %>

<div id="checkout_form">
<%= simple_form_for @order do |f| %>
    <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <h4> MY INFORMATION </h4>
    <%= f.hidden_field :user_id, value: current_user.id %>
    <p> Name: <%= current_user.proper_name %> </p>
    <p> Email: <%= current_user.email %> </p>
    <p> Phone: <%= current_user.phone %> </p>

    <h4> SHIP TO </h4>
  <span id="select_school"><%= f.input :school_id, :collection => School.active.alphabetical, :prompt => "Select School...", label: false %></span>

  <h4> PAYMENT INFORMATION </h4>
    <p style="width: 300px;">
      <%= f.text_field :credit_card_number, placeholder: 'Credit Card Number'  %>
      <%= f.text_field :expiration_month, placeholder: 'Expiration Month'  %>
      <%= f.text_field :expiration_year, placeholder: 'Expiration Year'  %>
    </p>
</div>
  <p><%= f.submit (@order.new_record? ? "Place Order" : "Update"), class: "button" %></p>

<% end %>

app/views/orders/_order_details.html.erb
<h3>
  <b>Order ID</b>: <%= @order.id %>
</h3><br>

<p>
  <b>Date</b>: <%= @order.date %>
</p>

<p>
  <b>School ID</b>: <%= @order.school_id %>
</p>

<p>
  <b>User ID</b>: <%= @order.user_id %>
</p>

<p>
  <b>Total Weight</b>: <%= @order.total_weight %>
</p>

<p>
  <b>Grand Total</b>: <%= number_to_currency(@order.grand_total)%>
</p>

<p>
  <b>Payment Receipt</b>: <%= @order.payment_receipt %>
</p>

app/views/orders/_order_items.html.erb
<% if @order_items.nil? || @order_items.empty? %>
  <h4>No order items in this order at this time.</h4>
<% else %>
  <h4>Order Items</h4>
  <table class="table table-striped">
    <thead>
      <tr>
        <th width="500">Item</th>
        <th width="150">Price</th>
        <th width="150">Quantity</th>
        <th width="150">Subtotal</th>
        <th width="300">Shipped On</th>
        <th> </th>
       
      </tr>
    </thead>
    <tbody>
      <% @order_items.each do |order_item| %>
        <tr>
          <td><%= link_to order_item.item.name, item_path(order_item.item) %></td>
          <td><%= number_to_currency(order_item.item.current_price) %></td>
          <td><%= order_item.quantity %></td>
          <td><%= number_to_currency(order_item.subtotal) %> </td>
          <td><%= order_item.shipped_on %> </td>
          <% if order_item.shipped_on.nil? %>
            <td> <%= link_to(class: 'button tiny radius', remote: true) do %> Ship <% end %> </td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>
<p>&nbsp;</p>

app/views/orders/_orders_index.html.erb
<% if @orders.nil? || @orders.empty? %>
  <!-- <h4>You have no orders at this time.</h4> -->
<% else %>
  <h3 id="center_heading">ALL ORDERS</h3> <hr/> <br/>
  <table class="table table-striped">
    <thead>
      <tr>
        <th width="100">Order ID</th>
        <th width="100">Date</th>
        <th width="250">School</th>
        <th width="175">User</th>
        <th width="125">Grand Total</th>
        <th width="200">Payment Confirmation</th>
      </tr>
    </thead>
    <tbody>
      <% @orders.each do |order| %>
        <tr>
          <td><%= link_to order.id, order_path(order), {:style=>'color: #bb892a;'} %></td>
          <td><%= order.date.strftime('%m/%d/%y') %></td>
          <td><%= order.school.name %></td>
          <td><%= link_to order.user.proper_name, user_path(order.user), {:style=>'color: #bb892a;'} %></td>
          
          <td><%= number_to_currency(order.grand_total)%></td>
          <td><%= order.payment_receipt %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

<%= will_paginate @orders, previous_label: "<&nbsp;", next_label: "&nbsp;>" %>

app/views/orders/index.html.erb
<% if current_user.role == "manager" || current_user.role == "admin" %>
    <%= render partial: "orders_index" %>
<% else %>
    <%= render partial: "my_orders" %>
<% end %>

app/views/orders/new.html.erb
<%= render :partial => "new_order_form" %>

app/views/orders/show.html.erb
<%= render partial: "partials/index_structure", locals: {model_name: "order", 
                                                         primary: "order_details", 
                                                         secondary: "order_items",
                                                         sidebar: nil} %>