config/routes.rb
Rails.application.routes.draw do
  
  # Routes for main resources
  resources :items
  resources :purchases
  resources :item_prices
  resources :users
  resources :orders
  resources :order_items
  resources :schools
  resources :sessions

  # authentication routes
  get 'user/edit' => 'users#edit', :as => :edit_current_user
  get 'signup' => 'users#new', :as => :signup
  get 'login' => 'home#home', :as => :login
  get 'logout' => 'sessions#destroy', :as => :logout

  get 'index' => 'carts#index', :as => :index
  get 'add_to_cart/:id' => 'carts#add_to_cart', :as => :add_to_cart
  get 'remove_from_cart/:id' => 'carts#remove_from_cart', :as => :remove_from_cart
  get 'destroy_order/:id' => 'orders#destroy', :as => :destroy_order

  # Semi-static page routes
  get 'home' => 'home#home', as: :home
  get 'about' => 'home#about', as: :about
  get 'contact' => 'home#contact', as: :contact
  get 'privacy' => 'home#privacy', as: :privacy
  patch 'ship/:id' => 'order_items#ship', as: :ship
  
  # Set the root url
  root :to => 'sessions#new', as: :root

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
    before_action :set_item, only: [:add_to_cart, :remove_from_cart]

    include ChessStoreHelpers::Cart

    def index 
        @cart_items = get_list_of_items_in_cart
        @total_cost = calculate_cart_items_cost
    end

    def add_to_cart
        add_item_to_cart(@item.id.to_s)
        redirect_to index_path
    end

    def remove_from_cart
        remove_item_from_cart(@item.id.to_s)
        redirect_to index_path
    end

    # def checkout
    #     clear_cart
    #     redirect_to new_order_path
    # end

    def set_item
        @item = Item.find(params[:id])
    end
end

app/views/carts/_order_form.html.erb
<%= form_for @order do |f| %>
    <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <p>
      <%= current_user.name %>
  </p>

  <h3> School Address </h3>
    <p>
      <%= f.label :name %><br />
      <%= f.text_field :name %>
    </p>
    <p>
      <%= f.label :street_1 %><br />
      <%= f.text_field :street_1 %>
    </p>
    <p>
      <%= f.label :street_2 %> <br />
      <%= f.text_field :street_2 %>
    </p>
    <p>
      <%= f.label :city %> <br />
      <%= f.text_field :city %>
    </p>
    <p>
      <%= f.label :state %> <br />
      <%= f.text_field :state %>
    </p>
    <p>
      <%= f.label :zip %> <br />
      <%= f.text_field :zip %>
    </p>
  <h3> Payment Information </h3>
    <p>
      <%= f.label :zip %> <br />
      <%= f.text_field :zip %>
    </p>
    <p>
      <%= f.label :zip %> <br />
      <%= f.text_field :zip %>
    </p>
    <p>
      <%= f.label :zip %> <br />
      <%= f.text_field :zip %>
    </p>

  
    
  <p><%= f.submit (@order.new_record? ? "Create" : "Update") %></p>
<% end %>

app/views/carts/add_to_cart.html.erb
<% unless @cart_items.nil? || @cart_items.empty? %>
  <table class="table table-striped">
    <thead>
      <tr>
        <th width="300">Order ID</th>
      </tr>
    </thead>
    <tbody>
      <% @cart_items.each do |item| %>
        <tr>
          <td><%= link_to item.name, item_path(item) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
    No items in the cart
<% end %>

app/views/carts/index.html.erb
<% unless @cart_items.nil? || @cart_items.empty? %>
  <h3 id="center_heading"> MY CART </h3> <hr/> <br/>
  <table class="table table-striped">
    <thead>
      <tr>
        <th width="300">Order ID</th>
        <th> Price </th>
        <th> Quantity </th>
        <th> Subtotal </th>
        <th> </th>
        <th width="50"> </th>
      </tr>
    </thead>
    <tbody>
      <% @cart_items.each do |order_item| %>
        <tr>
          <td><%= link_to order_item.item.name, item_path(order_item.item.id), {:style=>'color: #bb892a;'} %></td>
          <td> <%= number_to_currency(order_item.item.current_price) %> </td>
          <td> <%= order_item.quantity %> </td>
          <td> <%= number_to_currency(order_item.subtotal) %> </td>
          <td><%= link_to "Remove", remove_from_cart_path(order_item.item.id) %> </td>
          <td><%= link_to(add_to_cart_path(order_item.item.id), class: 'tiny alert button radius') do %>
            Add
          <% end %> </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <p> Order Subtotal : <%= number_to_currency(@total_cost) %> </p>
  <%= link_to(new_order_path, class: 'button radius') do %>
    Checkout
  <% end %>

<% else %>
    <h3 style="margin-left: 37%;"> NO ITEMS IN THE CART </h3> <hr/>
    <span style="margin-left: 42%;"><%= link_to(items_path, class: 'button radius') do %>
    SHOP NOW
  <% end %></span>
<% end %>